DROP TABLE IF EXISTS USERS;
 
CREATE TABLE USERS(
  id INT AUTO_INCREMENT  PRIMARY KEY,
 role_type VARCHAR(25) NOT NULL,
  user_name VARCHAR(25) NOT NULL,
  address VARCHAR(25) NOT NULL,
  book_issue VARCHAR(25) NOT NULL,
  book_return VARCHAR(25) NOT NULL

);

DROP TABLE IF EXISTS BOOKS;

CREATE TABLE BOOKS(
  id INT AUTO_INCREMENT  PRIMARY KEY,
  book_name VARCHAR(25) NOT NULL,
  book_title VARCHAR(25) NOT NULL,
  book_author VARCHAR(25) NOT NULL,
  book_publisher VARCHAR(25) NOT NULL,
  book_status VARCHAR(25) NOT NULL,
  book_return VARCHAR(25) NOT NULL

);


